### ISSUE TITLE
TypeError: cannot deepcopy this pattern object

### ISSUE THREAD

**Issue by hsj928** [openbmc/bmcweb#154]
What's the problem?

root@ubuntu:/home/ubuntu/bmcweb-docker-build/shared/bmcweb# ./build_x86.sh 
The Meson build system
Version: 0.55.3
Source dir: /home/ubuntu/bmcweb-docker-build/shared/bmcweb
Build dir: /home/ubuntu/bmcweb-docker-build/shared/bmcweb/builddir
Build type: native build
Project name: bmcweb
Project version: 1.0
C++ compiler for the host machine: c++ (gcc 5.4.0 "c++ (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609")
C++ linker for the host machine: c++ ld.bfd 2.26.1
Host machine cpu family: x86_64
Host machine cpu: x86_64
Compiler for C++ supports arguments -Wold-style-cast: YES 
Compiler for C++ supports arguments -Wcast-align: YES 
Compiler for C++ supports arguments -Wunused: YES 
Compiler for C++ supports arguments -Woverloaded-virtual: YES 
Compiler for C++ supports arguments -Wconversion: YES 
Compiler for C++ supports arguments -Wsign-conversion: YES 
Compiler for C++ supports arguments -Wno-attributes -Wattributes: YES 
Compiler for C++ supports arguments -DBOOST_ASIO_USE_TS_EXECUTOR_AS_DEFAULT: YES 
Compiler for C++ supports arguments -DBOOST_ASIO_DISABLE_THREADS: YES 
Compiler for C++ supports arguments -DBOOST_BEAST_USE_STD_STRING_VIEW: YES 
Compiler for C++ supports arguments -DBOOST_ERROR_CODE_HEADER_ONLY: YES 
Compiler for C++ supports arguments -DBOOST_SYSTEM_NO_DEPRECATED: YES 
Compiler for C++ supports arguments -DBOOST_ASIO_NO_DEPRECATED: YES 
Compiler for C++ supports arguments -DBOOST_ALL_NO_LIB: YES 
Compiler for C++ supports arguments -DBOOST_NO_RTTI: YES 
Compiler for C++ supports arguments -DBOOST_NO_TYPEID: YES 
Compiler for C++ supports arguments -DBOOST_COROUTINES_NO_DEPRECATION_WARNING: YES 
Compiler for C++ supports arguments -DBOOST_URL_STANDALONE: YES 
Compiler for C++ supports arguments -DBOOST_URL_HEADER_ONLY: YES 
Library pam found: YES
Library atomic found: YES
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Run-time dependency openssl found: YES 1.0.2g
Found CMake: /usr/bin/cmake (3.5.1)
Run-time dependency sdbusplus found: NO (tried pkgconfig and cmake)

|Executing subproject sdbusplus method meson 
|
|Project name: sdbusplus
|Project version: 1.0.0
|C compiler for the host machine: cc (gcc 5.4.0 "cc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609")
|C linker for the host machine: cc ld.bfd 2.26.1
|C++ compiler for the host machine: c++ (gcc 5.4.0 "c++ (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609")
|C++ linker for the host machine: c++ ld.bfd 2.26.1
|Run-time dependency libsystemd found: YES 229
|Program sdbus++ found: YES
|Program sdbus++-gendir found: YES
|Program sdbus++-gen-meson found: YES
|Run-time dependency Boost (found: context, coroutine) found: YES 1.58.0 (/usr)
|Build targets in project: 1
|Subproject sdbusplus finished.

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/mesonbuild/mesonmain.py", line 140, in run
    return options.run_func(options)
  File "/usr/local/lib/python3.5/dist-packages/mesonbuild/msetup.py", line 245, in run
    app.generate()
  File "/usr/local/lib/python3.5/dist-packages/mesonbuild/msetup.py", line 159, in generate
    self._generate(env)
  File "/usr/local/lib/python3.5/dist-packages/mesonbuild/msetup.py", line 192, in _generate
    intr.run()
  File "/usr/local/lib/python3.5/dist-packages/mesonbuild/interpreter.py", line 4560, in run
    super().run()
  File "/usr/local/lib/python3.5/dist-packages/mesonbuild/interpreterbase.py", line 493, in run
    self.evaluate_codeblock(self.ast, start=1)
  File "/usr/local/lib/python3.5/dist-packages/mesonbuild/interpreterbase.py", line 518, in evaluate_codeblock
    raise e
  File "/usr/local/lib/python3.5/dist-packages/mesonbuild/interpreterbase.py", line 511, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/usr/local/lib/python3.5/dist-packages/mesonbuild/interpreterbase.py", line 534, in evaluate_statement
    return self.evaluate_if(cur)
  File "/usr/local/lib/python3.5/dist-packages/mesonbuild/interpreterbase.py", line 615, in evaluate_if
    self.evaluate_codeblock(i.block)
  File "/usr/local/lib/python3.5/dist-packages/mesonbuild/interpreterbase.py", line 518, in evaluate_codeblock
    raise e
  File "/usr/local/lib/python3.5/dist-packages/mesonbuild/interpreterbase.py", line 511, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/usr/local/lib/python3.5/dist-packages/mesonbuild/interpreterbase.py", line 526, in evaluate_statement
    self.assignment(cur)
  File "/usr/local/lib/python3.5/dist-packages/mesonbuild/interpreterbase.py", line 1177, in assignment
    value = self.evaluate_statement(node.value)
  File "/usr/local/lib/python3.5/dist-packages/mesonbuild/interpreterbase.py", line 528, in evaluate_statement
    return self.method_call(cur)
  File "/usr/local/lib/python3.5/dist-packages/mesonbuild/interpreterbase.py", line 921, in method_call
    return obj.method_call(method_name, args, self.kwargs_string_keys(kwargs))
  File "/usr/local/lib/python3.5/dist-packages/mesonbuild/interpreterbase.py", line 39, in method_call
    return method(args, kwargs)
  File "/usr/local/lib/python3.5/dist-packages/mesonbuild/interpreterbase.py", line 286, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/mesonbuild/interpreterbase.py", line 213, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/mesonbuild/interpreter.py", line 510, in as_system_method
    new_dep = self.held_object.generate_system_dependency(new_is_system)
  File "/usr/local/lib/python3.5/dist-packages/mesonbuild/dependencies/base.py", line 235, in generate_system_dependency
    new_dep = copy.deepcopy(self)
  File "/usr/lib/python3.5/copy.py", line 166, in deepcopy
    y = copier(memo)
  File "/usr/local/lib/python3.5/dist-packages/mesonbuild/dependencies/base.py", line 261, in __deepcopy__
    setattr(result, k, copy.deepcopy(v, memo))
  File "/usr/lib/python3.5/copy.py", line 155, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.5/copy.py", line 218, in _deepcopy_list
    y.append(deepcopy(a, memo))
  File "/usr/lib/python3.5/copy.py", line 182, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/usr/lib/python3.5/copy.py", line 297, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python3.5/copy.py", line 155, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.5/copy.py", line 243, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.5/copy.py", line 182, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/usr/lib/python3.5/copy.py", line 297, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python3.5/copy.py", line 155, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.5/copy.py", line 243, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.5/copy.py", line 182, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/usr/lib/python3.5/copy.py", line 297, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python3.5/copy.py", line 155, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.5/copy.py", line 243, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.5/copy.py", line 182, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/usr/lib/python3.5/copy.py", line 297, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python3.5/copy.py", line 155, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.5/copy.py", line 243, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.5/copy.py", line 182, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/usr/lib/python3.5/copy.py", line 297, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python3.5/copy.py", line 155, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.5/copy.py", line 243, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.5/copy.py", line 166, in deepcopy
    y = copier(memo)
TypeError: cannot deepcopy this pattern object
NOTICE: You are using Python 3.5 which is EOL. Starting with v0.57, Meson will require Python 3.6 or newer
ninja: Entering directory `builddir'
ninja: error: loading 'build.ninja': No such file or directory

**Comment by edtanous** [comment]
This is relying on the old build script, which has had problems in the past.  The new build script relies on docker.

I suspect the right path forward here is to simply remove build_x86 from the repo.

**Comment by hsj928** [comment]
I installed oceore-x86_64-arm1176jzs-toolchain-nodistro. 0. Sh and the problem was solved.
